@startuml
title Процесс получения денег в банкомате

start
:Запрос карты и проверка пароля;
if (Пароль верный?) then (Да)
    :Проверка суммы;
    if (Сумма доступна на карте?) then (Да)
        #GREEN: Выдача денег;
        :Завершение процесса;
    kill
    else (Нет)
        #RED: Отказ в выдаче денег;
        :Завершение процесса;
    kill
    endif
else (Нет)
    #RED: Отказ;
    :Завершение процесса;
kill
endif
@enduml
