@startuml
title Вычисление корней квадратного уравнения

start
:Ввод уравнения квадратного вида;

if (a = 0 and b = 0) then (Ошибка)
    #RED:Отказ в вычислении корней;
    kill
elseif (a = 0 and b != 0) then (Ошибка)
    #RED:Отказ в вычислении корней;
    kill
elseif (a != 0 and b = 0) then (Ошибка)
    #RED:Отказ в вычислении корней;
    kill
elseif (a != 0 and b != 0) then (Вычисление корней)
    :Вычисление дискриминанта;
    if (Дискриминант > 0) then (Два различных корня)
        :Вычисление первого корня;
        :Вычисление второго корня;
        #GREEN: Отображение корней;
        kill
    elseif (Дискриминант = 0) then (Один общий корень)
        :Вычисление корня;
        #GREEN: Отображение корня;
        kill
    else (Корней не существуют)
        #RED: Отказ в вычислении корней;
        kill
    endif
else (Ошибка)
    #RED :Отказ в вычислении корней;
    kill
endif
@enduml
