@startuml one
start
:Клиент вставляет карту в банкомат;
if (Клиент вводит пароль) then (Пароль верный)
if (Проверка суммы) then (Успешно)
:Клиенту выдали деньги; 
kill
else (Недостаточно средств)
:Ошибка;
kill
endif
else (Пароль неверный)
:Ошибка;
kill
endif
@enduml