@startuml
start
:вставить карту в банкомат;
:ввести пароль;
if (Пароль верный) then (да)
:проверить сумму;
if (Верная сумма) then (да)
if (Достаточная ли сумма) then (да)
:выдача средств
:забрать деньги;
:забрать карту;
else (нет)
:Ошибка(недостаточно средств);
:Забрать карту;
endif
else (нет)
:Ошибка(ошибка проверки суммы);
:Забрать карту;
endif
else (нет)
:Ошибка(ошибка проверки пароля);
:Забрать карту;
endif
stop

@enduml
