@startuml

start 
:ввести коэфиценты a,b,c;
:Вычислить дискрименант D;
if (D>0) then (Два корня)
:вычеслить первый корень x;
:вычеслить второй корень y;
:вывести значение корней;
else if (D = 0) then (один корень)
:вычеслить корень x;
:вывод значения корня;
else (Нет корней)
:корни отсутствуют;
endif
stop

@enduml

